package com.arttvad.worktime.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF4F5FC7)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDEE1FF)
val LightOnPrimaryContainer = Color(0xFF0A195A)
val LightSecondary = Color(0xFF5C5D72)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE1E0F9)
val LightOnSecondaryContainer = Color(0xFF191A2C)
val LightBackground = Color(0xFFFBF8FF)
val LightOnBackground = Color(0xFF1B1B21)
val LightSurface = Color(0xFFFBF8FF)
val LightOnSurface = Color(0xFF1B1B21)
val LightSurfaceVariant = Color(0xFFE4E1EC)
val LightOnSurfaceVariant = Color(0xFF47464F)
val LightOutline = Color(0xFF777680)
val LightOutlineVariant = Color(0xFFC8C5D0)

val DarkPrimary = Color(0xFFBBC3FF)
val DarkOnPrimary = Color(0xFF1D2F8F)
val DarkPrimaryContainer = Color(0xFF3747AA)
val DarkOnPrimaryContainer = Color(0xFFDEE1FF)
val DarkSecondary = Color(0xFFC5C4DD)
val DarkOnSecondary = Color(0xFF2E2F42)
val DarkSecondaryContainer = Color(0xFF444559)
val DarkOnSecondaryContainer = Color(0xFFE1E0F9)
val DarkBackground = Color(0xFF121318)
val DarkOnBackground = Color(0xFFE5E1E9)
val DarkSurface = Color(0xFF121318)
val DarkOnSurface = Color(0xFFE5E1E9)
val DarkSurfaceVariant = Color(0xFF47464F)
val DarkOnSurfaceVariant = Color(0xFFC8C5D0)
val DarkOutline = Color(0xFF91909A)
val DarkOutlineVariant = Color(0xFF47464F)
